apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: scara-dotnet-web-app-pipeline-
spec:
  # serviceAccountName: build-bot
  pipelineRef:
    name: scara-dotnet-web-app-pipeline
  workspaces:
  - name: pipeline-shared-data
    volumeClaimTemplate: 
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi